from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1366, 768)
        MainWindow.setStyleSheet("background-color: rgb(20, 35, 58);\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(-4, 101, 1370, 3))
        self.line.setStyleSheet("background-color: #858585")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(445, 20, 476, 69))
        font = QtGui.QFont()
        font.setFamily("Forte")
        font.setPointSize(30)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #ffffff")
        self.label.setObjectName("label")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(713, 101, 3, 670))
        self.line_2.setStyleSheet("background-color: #858585")
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(67, 157, 566, 355))
        self.label_2.setStyleSheet("background-color: #D9D9D9")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(71, 572, 566, 161))
        self.label_3.setStyleSheet("background-color: #D9D9D9")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(787, 157, 270, 355))
        self.label_4.setStyleSheet("background-color: #D9D9D9")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(71, 126, 94, 25))
        font = QtGui.QFont()
        font.setFamily("Forte")
        font.setPointSize(17)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: #ffffff")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(71, 538, 152, 25))
        font = QtGui.QFont()
        font.setFamily("Forte")
        font.setPointSize(17)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: #ffffff")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(1081, 180, 71, 25))
        font = QtGui.QFont()
        font.setFamily("Forte")
        font.setPointSize(17)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: #ffffff")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(1081, 240, 71, 25))
        font = QtGui.QFont()
        font.setFamily("Forte")
        font.setPointSize(17)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: #ffffff")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(1081, 370, 62, 25))
        font = QtGui.QFont()
        font.setFamily("Forte")
        font.setPointSize(17)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: #ffffff")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(1081, 310, 62, 25))
        font = QtGui.QFont()
        font.setFamily("Forte")
        font.setPointSize(17)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: #ffffff")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(1081, 430, 94, 25))
        font = QtGui.QFont()
        font.setFamily("Forte")
        font.setPointSize(17)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: #ffffff")
        self.label_11.setObjectName("label_11")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(1152, 675, 158, 61))
        font = QtGui.QFont()
        font.setFamily("Forte")
        font.setPointSize(17)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: #D9D9D9")
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Automated Attendance Tracking"))
        self.label.setText(_translate("MainWindow", "Attendance tracking System"))
        self.label_5.setText(_translate("MainWindow", "Live Video"))
        self.label_6.setText(_translate("MainWindow", "Attendance Log"))
        self.label_7.setText(_translate("MainWindow", "Name:"))
        self.label_8.setText(_translate("MainWindow", "Grade:"))
        self.label_9.setText(_translate("MainWindow", "Date:"))
        self.label_10.setText(_translate("MainWindow", "Time:"))
        self.label_11.setText(_translate("MainWindow", "Strand:"))
        self.pushButton.setText(_translate("MainWindow", "Login"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
